### ISSUE TITLE
User issue: capital/lower case defaults

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#269] opened 2015-09-08 15:26 UTC
> in the data form, in the mobile version I have just used, there is inconsistency in default case for letters:
> Email address defaults to initial capital - which is weird and led to me having a discrepancy. 
> Postcode does not default to All Capitals, which is a bore. 

Don't know if there's anything we can do about that?

**Comment by dracos** [comment] 2015-09-08 16:12
Doesn't matter what case they use for postcode; email is dupe of #256.

**Comment by zarino** [comment] 2015-09-16 06:48
I think we can make the postcode input *look* like it's all in capitals by giving it:

```
input#pc {
    text-transform: uppercase;
}
```

In reality, the contents of the text input will still be lowercase, but they'll *look* to the user like they're uppercase.

**Comment by dracos** [comment] 2015-09-17 13:42
Thanks for the idea, @zarino!

**Closed** 2015-09-17 13:41 UTC
Labels: Design
