### ISSUE TITLE
User request: allow Scottish users to contact all MSPs at once

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#212] opened 2014-11-13 09:25 UTC
" I am puzzled as to why you don't let me and other people in
     Scotland write to their list and constituency MSPs at the same
     time.  While there will be some local issues that are relevant
     only for a constituency MSP,  broader political issues,about
     priorites for public spending, for example,  are the concern of
     ALL MSPs, and I often find myself having to write 2 emails
     instead of one, because you won't allow me to send my email to
     all of them together.  Given that in many parts of Scotland, it
     is the local MSP who is SNP, i.e represents the  Scottish
     Government,  whereas the list MSPs are mainly from opposition
     parties, you can see how important it is that the local MSP is
     included as well!"

**Comment by MyfanwyNixon** [comment] 2015-01-15 09:26
Another user: "Firstly, and specifically relating to MSPs, as you know there are two types of MSP: constituency and list.  Currently you can write to either your constituency MSP or your list MSPs.  I would like the ability to write to all my MSPs in a single message.  That way, I can send a message that is of relevance to all of them in one go (for example, if I want to ask all my MSPs to support an upcoming Bill in Parliament, there's no point sending two separate messages).

Secondly, for situations where you are writing to a group of people (either the Scottish list MSPs or local councillors), I would like to be able to exclude certain recipients from the email.  Again, taking the example above, if one of my MSPs is the one proposing a Bill, it seems a bit pointless in including them in an email asking for support for that Bill."

**Comment by dracos** [comment] 2015-01-15 09:44
Second point of latest update is a different issue, so could ticket separately; I think it wouldn't be trivial to add (possible though, little X by each name or something similar I guess).

First point, this ticket – WTT has only ever done "all" messages to one type of representative (e.g. same in London, you can write to all the list members or the constituency AM, not both). It's been so rarely requested, and as noted by the person they can send two separate messages if needed. I know the MSPs really dislike messages to them all unnecessarily, hence the warnings they've asked us to add over the years.

**Comment by MyfanwyNixon** [comment] 2015-01-15 10:50
I'll make a second ticket for the second point.

**Comment by MyfanwyNixon** [comment] 2015-02-03 09:59
User comment: "I am wanting to write to all my MSPs (Constituency MSP
     plus all Regional MSPs) about a voting matter in the Scottish
     Parliament but it seems there is no such option. It seems I can
     have any single MSP or all the regional MSPs but not the
     Constituency MSP and Regional ones. This means I need to
     prepare two identical communications.

     I want to say something like -

     In the ongoing budget discussions please raise X with the govt
     and let me know the outcome."

**Comment by abimysoc** [comment] 2015-03-16 14:23
Dupe of #104.

**Closed by abimysoc** 2015-03-16 14:23 UTC
